import json
import time
from pathlib import Path
from typing import Dict, Optional, Tuple

# In-memory storage for lab tokens
LAB_TOKENS: Dict[str, dict] = {}

# File-based persistence (hedge against server restart)
_LAB_TOKENS_FILE = Path(__file__).parent.parent / "logs" / "lab_tokens.json"


def _persist_tokens():
    try:
        _LAB_TOKENS_FILE.parent.mkdir(parents=True, exist_ok=True)
        serializable = {}
        for token, data in LAB_TOKENS.items():
            serializable[token] = {
                "treatment_group": data.get("treatment_group", 0),
                "group_index": data.get("group_index", 0),
                "created_at": data.get("created_at", 0),
                "used": data.get("used", False),
            }
        with open(_LAB_TOKENS_FILE, "w") as f:
            json.dump(serializable, f, indent=2)
    except Exception as e:
        print(f"Warning: failed to persist lab tokens: {e}")


def _load_tokens():
    global LAB_TOKENS
    try:
        if _LAB_TOKENS_FILE.exists():
            with open(_LAB_TOKENS_FILE, "r") as f:
                data = json.load(f)
            for token, info in data.items():
                if token not in LAB_TOKENS:
                    LAB_TOKENS[token] = info
    except Exception as e:
        print(f"Warning: failed to load lab tokens: {e}")


# Load any persisted tokens on module import
_load_tokens()


def generate_lab_tokens(count: int, base_url: str = "", num_treatments: int = 1) -> list:
    """Generate lab tokens with human-readable format T{treatment}_P{participant}.

    Tokens are distributed across treatment groups in blocks.
    E.g. count=6, num_treatments=2 → T1_P1, T1_P2, T1_P3, T2_P1, T2_P2, T2_P3
    Treatment numbers are 1-based in the token string.
    """
    links = []
    block_size = count // num_treatments if num_treatments > 1 else count
    for i in range(count):
        treatment_group = i // block_size if num_treatments > 1 else 0
        if treatment_group >= num_treatments:
            treatment_group = num_treatments - 1
        # group_index is 0-based position within the treatment group
        group_index = i - (treatment_group * block_size)

        # Token format: T{treatment+1}_P{group_index+1} (1-based for readability)
        token = f"T{treatment_group + 1}_P{group_index + 1}"

        LAB_TOKENS[token] = {
            "treatment_group": treatment_group,
            "group_index": group_index,
            "created_at": time.time(),
            "used": False,
        }
        if base_url:
            links.append(f"{base_url}?LAB={token}")
        else:
            links.append(token)
    _persist_tokens()
    return links


def validate_lab_token(token: str) -> Tuple[bool, Optional[dict]]:
    if token not in LAB_TOKENS:
        # Try reloading from file in case tokens were generated by another process
        _load_tokens()
    if token not in LAB_TOKENS:
        return False, None

    info = LAB_TOKENS[token]

    # Mark as used on first validation
    if not info["used"]:
        info["used"] = True
        _persist_tokens()

    treatment_group = info["treatment_group"]
    group_index = info["group_index"]
    # Use the token itself as the readable username/trader suffix
    trader_id = f"HUMAN_LAB_{token}"

    user = {
        "uid": f"lab_{token}",
        "email": f"lab_{token}@lab.local",
        "gmail_username": f"LAB_{token}",
        "is_admin": False,
        "is_lab": True,
        "lab_token": token,
        "trader_id": trader_id,
        "treatment_group": treatment_group,
        "group_index": group_index,
    }
    return True, user


# Global mapping of lab trader_ids to user data (populated on login)
lab_trader_map: Dict[str, dict] = {}
